# Generated by Django 4.1.7 on 2023-05-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RealEstateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'verbose_name': 'Объект недвижимости', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
        migrations.AddField(
            model_name='realestate',
            name='rooms',
            field=models.IntegerField(default=2, verbose_name='Кол-во комнат'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realestate',
            name='district',
            field=models.CharField(choices=[('Советский', 'Советский'), ('Приволжский', 'Приволжский'), ('Вахитовский', 'Вахитовский'), ('Московский', 'Московский'), ('Авиастроительный', 'Авиастроительный'), ('Ново - Савиновский', 'Ново - Савиновский')], max_length=70, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='finishing',
            field=models.CharField(choices=[('Без отделки', 'Без отделки'), ('под чистовую отделку', 'под чистовую отделку'), ('Косметический', 'Косметический'), ('Капитальный', 'Капитальный'), ('евроремонт', 'евроремонт'), ('ремонт премиум-класса', 'ремонт премиум-класса')], max_length=70, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='realtor',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Риелтор'),
        ),
    ]
