# Generated by Django 4.1.7 on 2023-05-16 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RealEstateApp', '0002_alter_category_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Дата и время бронирования')),
                ('is_available', models.BooleanField(default=True, verbose_name='Статус')),
            ],
        ),
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=15, verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.realestate', verbose_name='Объект для брони')),
                ('realtor', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Риелтор')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.timeslot', verbose_name='Время бронирования')),
            ],
        ),
    ]
