# Generated by Django 4.1.7 on 2023-06-05 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RealEstateApp', '0004_alter_booking_options_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('price', models.DecimalField(decimal_places=1, max_digits=15, verbose_name='Стоимость')),
                ('date', models.DateField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.realestate', verbose_name='Объект')),
                ('realtor', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Риелтор')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
    ]
